x-rinha-de-backend-default: &rinha-de-backend-default
  image: thiagorts/rinha-de-backend:${APP_TAG}
  build:
    context: ./
    args:
      - PYTHON_TAG=${PYTHON_TAG}
  restart: always
  expose:
    - "8000"
  depends_on:
    - db
  deploy:
    resources:
      limits:
        cpus: "0.25"
        memory: "0.5GB"


services:

  nginx:
    image: nginx:${NGINX_TAG}
    restart: always
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"

  app0:
    <<: *rinha-de-backend-default
    hostname: app0
    restart: "no"
    env_file:
      - ./compose/app1/.env
    command: ./manage.py migrate && exit 0

  app1:
    <<: *rinha-de-backend-default
    hostname: app1
    env_file:
      - ./compose/app1/.env
    depends_on:
      - db
      - app0

  app2:
    <<: *rinha-de-backend-default
    hostname: app2
    env_file:
      - ./compose/app2/.env
    depends_on:
      - db
      - app0

  db:
    image: postgres:${PG_TAG}
    restart: always
    volumes:
      - ./compose/db/init:/docker-entrypoint-initdb.d:rw
      - ./compose/db/data:/var/lib/postgresql/data:rw
    env_file:
      - ./compose/db/.env
    command: postgres -c max_connections=200 -c shared_buffers=256
    expose:
      - "5432"
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1.5GB"
