
services:
  db:
    image: postgres:latest
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:rw
      - ./db/data:/var/lib/postgresql/data:rw
    env_file:
      - ./db/.env
    command: postgres -c max_connections=1000 -c shared_buffers=256
    ports:
      - 6543:5432
