
services:
  db:
    image: postgres:latest
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:rw
      - ./db/data:/var/lib/postgresql/data:rw
    env_file:
      - ./db/.env
    ports:
      - 6543:5432
