# Generated by Django 4.2.5 on 2023-10-04 14:01

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_pessoa_search_field'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pessoa',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_field'], name='pessoas_pes_search__6d23a4_gin'),
        ),
    ]
