# Generated by Django 4.2.5 on 2024-01-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_pessoa_pessoas_pes_search__6d23a4_gin'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE pessoas_pessoa ADD COLUMN search_row varchar GENERATED ALWAYS AS (
                        lower(apelido || ' ' || nome || ' ' || array_to_string_immutable(stack, ' ', ''))
                    ) STORED;
                    """,
                    reverse_sql="ALTER TABLE pessoas_pessoa DROP COLUMN search_field ;"
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='pessoa',
                    name='search_row',
                    field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Search Row'),
                ),
            ],
        ),
    ]
