# Generated by Django 4.2.5 on 2024-01-29 20:24

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_pessoa_search_row'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pessoa',
            index=django.contrib.postgres.indexes.GistIndex(fields=['search_row'], name='pessoas_pes_search__1a433c_gist', opclasses=['gist_trgm_ops']),
        ),
    ]
