# Generated by Django 4.2.11 on 2024-03-21 20:12

from django.db import migrations, models
import pessoas.models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_pessoa_pessoas_pes_search__1a433c_gist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='stack',
            field=pessoas.models.ArrayField(base_field=models.CharField(max_length=32), null=True, size=None, verbose_name='Stack'),
        ),
    ]
